// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdVk9qX6QasIR59ubIlBstwoO5gvjmJs8',
    appId: '1:787311133272:web:04b901a8066fc5691a802d',
    messagingSenderId: '787311133272',
    projectId: 'restaurantapp-albe',
    authDomain: 'restaurantapp-albe.firebaseapp.com',
    storageBucket: 'restaurantapp-albe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiDDFIcz-bltNYx2jHCl41E5rqLod2n-g',
    appId: '1:787311133272:android:bf389349e1d4c3641a802d',
    messagingSenderId: '787311133272',
    projectId: 'restaurantapp-albe',
    storageBucket: 'restaurantapp-albe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCS5oPuMAaT5zKJB_ETvvT5i-UFWXWcIQ',
    appId: '1:787311133272:ios:b0c23aed365e4fc31a802d',
    messagingSenderId: '787311133272',
    projectId: 'restaurantapp-albe',
    storageBucket: 'restaurantapp-albe.appspot.com',
    iosClientId: '787311133272-icr2btpqtg2ptomn050effr144qm29ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.restappAutoma',
  );
}
