// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Kyc3x0cv_SJwiktn7h3dbDbci01GWOI',
    appId: '1:421775087736:web:cca9ae9792961b1597358d',
    messagingSenderId: '421775087736',
    projectId: 'restapp-automa',
    authDomain: 'restapp-automa.firebaseapp.com',
    storageBucket: 'restapp-automa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFcOLxKf0Y5DCSADbUowhRZ9N8u-Eo3E0',
    appId: '1:421775087736:android:67d85c63230998c497358d',
    messagingSenderId: '421775087736',
    projectId: 'restapp-automa',
    storageBucket: 'restapp-automa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPumqs2CyXbPaeoMMmNn3iOX7AJc1lta8',
    appId: '1:421775087736:ios:8bbe32ce45535a1197358d',
    messagingSenderId: '421775087736',
    projectId: 'restapp-automa',
    storageBucket: 'restapp-automa.appspot.com',
    iosClientId: '421775087736-k1cstadqqc40s7tf1hahv5alekbvjj5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.restappAutoma',
  );
}
